-- klar · Migration 0004
-- File attachments per project. Files live in Supabase Storage (bucket
-- "project-files"), metadata lives here. 10MB per file, enforced both in the
-- client upload path and as a defense-in-depth check via file size column.

create table project_files (
  id           uuid primary key default gen_random_uuid(),
  project_id   uuid not null references projects (id) on delete cascade,
  file_name    text not null,
  storage_path text not null, -- {studio_id}/{project_id}/{uuid}-{filename}
  size_bytes   bigint not null check (size_bytes > 0 and size_bytes <= 10 * 1024 * 1024),
  content_type text,
  uploaded_by  text not null default 'studio', -- 'studio' | future: 'client'
  created_at   timestamptz not null default now()
);

create index on project_files (project_id);

alter table project_files enable row level security;

create policy project_files_all on project_files
  for all using (owns_project(project_id)) with check (owns_project(project_id));

-- ---------------------------------------------------------------------------
-- Storage bucket: private (no public read). Studio uploads/manages via RLS
-- on storage.objects keyed by studio_id, same pattern as avatars. The
-- portal reads files exclusively through portal_get_client, which returns
-- signed URLs generated server-side with the service role — the bucket
-- itself stays private so a leaked path alone grants nothing.
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('project-files', 'project-files', false)
on conflict (id) do nothing;

create policy "project_files_studio_read"
  on storage.objects for select
  using (
    bucket_id = 'project-files'
    and is_studio_owner(((storage.foldername(name))[1])::uuid)
  );

create policy "project_files_studio_write"
  on storage.objects for insert
  with check (
    bucket_id = 'project-files'
    and is_studio_owner(((storage.foldername(name))[1])::uuid)
  );

create policy "project_files_studio_delete"
  on storage.objects for delete
  using (
    bucket_id = 'project-files'
    and is_studio_owner(((storage.foldername(name))[1])::uuid)
  );

-- ---------------------------------------------------------------------------
-- Portal: list files per project with a short-lived signed URL each.
-- Runs with service_role so it can call storage.create_signed_url-equivalent
-- via the storage schema's signing function.
-- ---------------------------------------------------------------------------

create or replace function portal_get_client(p_project_id uuid) returns jsonb
language sql stable security definer set search_path = public, extensions as $$
  select jsonb_build_object(
    'client', jsonb_build_object('name', c.name),
    'studio', jsonb_build_object(
      'name', s.name,
      'logo_url', s.logo_url,
      'accent_color', s.accent_color
    ),
    'welcome_message', c.welcome_message,
    'project_lead', (
      select jsonb_build_object('name', tm.name, 'photo_url', tm.photo_url)
      from team_members tm where tm.id = c.project_lead_id
    ),
    'projects', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', p2.id,
        'name', p2.name,
        'status', p2.status,
        'description', p2.description,
        'deadline', p2.deadline,
        'files', coalesce((
          select jsonb_agg(jsonb_build_object(
            'id', f.id,
            'file_name', f.file_name,
            'size_bytes', f.size_bytes,
            'storage_path', f.storage_path
          ) order by f.created_at)
          from project_files f where f.project_id = p2.id
        ), '[]'::jsonb)
      ) order by p2.position)
      from projects p2
      where p2.client_id = c.id and p2.archived_at is null
    ), '[]'::jsonb)
  )
  from projects p
  join studios s on s.id = p.studio_id
  join clients c on c.id = p.client_id
  where p.id = p_project_id and p.archived_at is null;
$$;

revoke execute on function portal_get_client(uuid) from public, anon, authenticated;
grant execute on function portal_get_client(uuid) to service_role;

-- Note: signed download URLs are generated by the portal server via the
-- Supabase Storage client (createSignedUrl), not from SQL — the storage
-- schema's internal signing function is not a stable public API to call
-- directly from Postgres. See portal/lib/server.ts.
